# Model 
obs_dim: 56
action_dim: 6
input_dim: 56
output_dim: 6
batch_size: 64
hidden_dim: 512
# Train 
epochs: 20
lr: 0.00007
weight_decay: 0.000001
# Evaluation 
deterministic: false
num_ep: 50
video_dir: 'media/good_mlp.mp4'